[package]
name = "num"
version = "0.1.0"
edition = "2024"

[dependencies]
device_query = "4.0.1"
enigo = "0.6.1"
chrono = "0.4.43"
rand = "0.9.2"
winapi = { version = "0.3.9", features = ["winuser", "wincon"] }